/*
* generated by Xtext
*/
package biz.vidal.protobuf4e.labeling;

import org.eclipse.xtext.ui.core.DefaultLabelProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class ProtobufLabelProvider extends DefaultLabelProvider {
/*
	
	//Labels and icons can be computed like this:
	
	String text(MyModel ele) {
	  return "my "+ele.getName();
	}
	 
    String image(MyModel ele) {
      return "MyModel.gif";
    }
	 
*/
}
