/*
 * generated by Xtext
 */
package biz.vidal.protobuf4e;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ProtobufUiModule extends biz.vidal.protobuf4e.AbstractProtobufUiModule {

}
