/*
* generated by Xtext
*/
package biz.vidal.protobuf4e.contentassist;

import biz.vidal.protobuf4e.contentassist.AbstractProtobufProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ProtobufProposalProvider extends AbstractProtobufProposalProvider {

}
