/*
* generated by Xtext
*/
package biz.vidal.protobuf4e.outline;

import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class ProtobufTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
